<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class productSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('products')->insert([
        //1
            [
                'category_id' => 1,
                'discount_id' => null,
                'name' => 'Dâu Tây',
                'description' => 'Dâu tây tươi ngon, mọng nước, vị ngọt thanh, giàu vitamin C và chất chống oxy hóa, giúp tăng cường sức khỏe và làm đẹp da.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Đà Lạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //2
            [
                'category_id' => 1,
                'discount_id' => null,
                'name' => 'Táo Cherry',
                'description' => 'Táo cherry giòn, ngọt, giàu chất xơ và vitamin, giúp cải thiện tiêu hóa và tăng cường hệ miễn dịch.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Mỹ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //3
            [
                'category_id' => 2,
                'discount_id' => null,
                'name' => 'Nấm Kim Châm',
                'description' => 'Nấm kim châm tươi, giòn, giàu protein và chất xơ, giúp hỗ trợ tiêu hóa và tăng cường sức khỏe tim mạch.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Đà Lạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //4
            [
                'category_id' => 2,
                'discount_id' => null,
                'name' => 'Rau Muống',
                'description' => 'Rau muống xanh mướt, giòn ngon, giàu vitamin A và C, giúp tăng cường thị lực và hệ miễn dịch.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Đà Lạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //5
            [
                'category_id' => 4,
                'discount_id' => null,
                'name' => 'Bột ngũ cốc',
                'description' => 'Bột ngũ cốc dinh dưỡng, giàu chất xơ và protein, giúp cung cấp năng lượng và hỗ trợ tiêu hóa.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Việt Nam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //6
            [
                'category_id' => 4,
                'discount_id' => null,
                'name' => 'Yến mạch gạo lứt',
                'description' => 'Yến mạch gạo lứt nguyên chất, giàu chất xơ và vitamin, giúp kiểm soát cân nặng và cải thiện sức khỏe tim mạch.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Việt Nam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //7
            [
                'category_id' => 2,
                'discount_id' => null,
                'name' => 'Bắp cải xanh',
                'description' => 'Bắp cải xanh tươi ngon, giòn, giàu vitamin K và C, giúp tăng cường hệ miễn dịch và hỗ trợ tiêu hóa.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Đà Lạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //8
            [
                'category_id' => 4,
                'discount_id' => null,
                'name' => 'Bún gạo lứt',
                'description' => 'Bún gạo lứt mềm dai, giàu chất xơ và dinh dưỡng, giúp hỗ trợ tiêu hóa và cung cấp năng lượng cho cơ thể.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Việt Nam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //9
            [
                'category_id' => 2,
                'discount_id' => null,
                'name' => 'Bông cải xanh',
                'description' => 'Bông cải xanh tươi ngon, giòn, giàu vitamin C và chất chống oxy hóa, giúp tăng cường hệ miễn dịch và bảo vệ tế bào khỏi tổn thương.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Đà Lạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //10
            [
                'category_id' => 2,
                'discount_id' => null,
                'name' => 'Ớt chuông',
                'description' => 'Ớt chuông giòn, ngọt, giàu vitamin A và C, giúp tăng cường hệ miễn dịch và cải thiện sức khỏe da.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Đà Lạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //11
            [
                'category_id' => 2,
                'discount_id' => null,
                'name' => 'Dưa chuột gai',
                'description' => 'Dưa chuột gai tươi mát, giòn ngon, giàu nước và chất xơ, giúp thanh lọc cơ thể và hỗ trợ tiêu hóa.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Đà Lạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //12
            [
                'category_id' => 2,
                'discount_id' => null,
                'name' => 'Cà tím',
                'description' => 'Cà tím tươi ngon, giàu chất chống oxy hóa và chất xơ, giúp cải thiện tiêu hóa và hỗ trợ sức khỏe tim mạch.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Đà Lạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //13
            [
                'category_id' => 2,
                'discount_id' => null,
                'name' => 'Cà chua',
                'description' => 'Cà chua đỏ mọng, giàu lycopene và vitamin C, giúp bảo vệ tim mạch và tăng cường hệ miễn dịch.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Đà Lạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //14
            [
                'category_id' => 1,
                'discount_id' => null,
                'name' => 'Chuối tiêu',
                'description' => 'Chuối tiêu chín mọng, ngọt thơm, giàu kali và vitamin B6, giúp cung cấp năng lượng và hỗ trợ chức năng thần kinh.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Đồng Nai',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //15
            [
                'category_id' => 1,
                'discount_id' => null,
                'name' => 'Cam sành',
                'description' => 'Cam sành mọng nước, ngọt thanh, giàu vitamin C và chất chống oxy hóa, giúp tăng cường hệ miễn dịch và làm đẹp da.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Vĩnh Long',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //16
            [
                'category_id' => 1,
                'discount_id' => null,
                'name' => 'Nho đen không hạt',
                'description' => 'Nho đen không hạt ngọt lịm, mọng nước, giàu resveratrol và chất chống oxy hóa, giúp bảo vệ tim mạch và tăng cường sức khỏe tổng thể.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Mỹ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //17
            [
                'category_id' => 1,
                'discount_id' => null,
                'name' => 'Dưa hấu',
                'description' => 'Dưa hấu ngọt mát, mọng nước, giàu lycopene và vitamin C, giúp thanh lọc cơ thể và tăng cường hệ miễn dịch.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Tiền Giang',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //18
            [
                'category_id' => 1,
                'discount_id' => null,
                'name' => 'Lê Hàn Quốc',
                'description' => 'Lê Hàn Quốc giòn ngọt, mọng nước, giàu chất xơ và vitamin C, giúp cải thiện tiêu hóa và tăng cường hệ miễn dịch.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Hàn Quốc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //19
            [
                'category_id' => 1,
                'discount_id' => null,
                'name' => 'Đào',
                'description' => 'Đào tươi ngon, ngọt mát, giàu vitamin A và C, giúp cải thiện thị lực và tăng cường hệ miễn dịch.',
                'status'=>'còn hàng',
                'active'=> 'đang bán',
                'hot'=>0,
                'origin'=>'Đà Lạt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //20
            [
                'category_id' => 3,
                'discount_id' => null,
                'name' => 'Bắp bò',
                'description' => 'Bắp bò tươi ngon, giàu protein và sắt, giúp cung cấp năng lượng và hỗ trợ sức khỏe cơ bắp.',
                'status'=>'còn hàng',
                'active'=> 'đang bán',
                'hot'=>0,
                'origin'=>'Việt Nam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //21
            [
                'category_id' => 3,
                'discount_id' => null,
                'name' => 'Cá hồi',
                'description' => 'Cá hồi tươi ngon, giàu omega-3 và protein, giúp cải thiện sức khỏe tim mạch và não bộ.',
                'status'=>'còn hàng',
                'active'=> 'đang bán',
                'hot'=>0,
                'origin'=>'Na Uy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //22
            [
                'category_id' => 3,
                'discount_id' => null,
                'name' => 'Hàu sữa',
                'description' => 'Hàu sữa tươi ngon, giàu kẽm và vitamin B12, giúp tăng cường hệ miễn dịch và hỗ trợ sức khỏe sinh sản.',
                'status'=>'còn hàng',
                'active'=>'đang bán',
                'hot'=>0,
                'origin'=>'Phú Yên',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //23
            [
                'category_id' => 3,
                'discount_id' => null,
                'name' => 'Kobe A5',
                'description' => 'Kobe A5 thượng hạng, thịt mềm mỡ lừ, giàu protein và chất béo lành mạnh, giúp cung cấp năng lượng và hỗ trợ sức khỏe tim mạch.',
                'status'=>'còn hàng',
                'active'=> 'đang bán',
                'hot'=>0,
                'origin'=>'Nhật Bản',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //24
            [
                'category_id' => 3,
                'discount_id' => null,
                'name' => 'Mực ống',
                'description' => 'Mực ống tươi ngon, giàu protein và khoáng chất, giúp cải thiện sức khỏe cơ bắp và hỗ trợ chức năng não bộ.',
                'status'=>'còn hàng',
                'active'=> 'đang bán',
                'hot'=>0,
                'origin'=>'Phú Yên',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //25
            [
                'category_id' => 3,
                'discount_id' => null,
                'name' => 'Sườn heo',
                'description' => 'Sườn heo tươi ngon, giàu protein và vitamin B, giúp cung cấp năng lượng và hỗ trợ sức khỏe cơ bắp.',
                'status'=>'còn hàng',
                'active'=> 'đang bán',
                'hot'=>0,
                'origin'=>'Việt Nam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //26
            [
                'category_id' => 3,
                'discount_id' => null,
                'name' => 'Thịt lợn',
                'description' => 'Thịt lợn tươi ngon, giàu protein và vitamin B, giúp cung cấp năng lượng và hỗ trợ sức khỏe cơ bắp.',
                'status'=>'còn hàng',
                'active'=> 'đang bán',
                'hot'=>0,
                'origin'=>'Việt Nam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        //27
            [
                'category_id' => 3,
                'discount_id' => null,
                'name' => 'Thịt bò',
                'description' => 'Thịt bò tươi ngon, giàu protein và sắt, giúp cung cấp năng lượng và hỗ trợ sức khỏe cơ bắp.',
                'status'=>'còn hàng',
                'active'=> 'đang bán',
                'hot'=>0,
                'origin'=>'Việt Nam',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
