<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class variantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('variants')->insert([
            [
                'product_id'=> 1,
                'img_id'=> 1,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 100000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 1,
                'img_id'=> 1,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 150000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 1,
                'img_id'=> 1,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 200000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 1,
                'img_id'=> 1,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 200000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 2,
                'img_id'=> 2,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 40000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 2,
                'img_id'=> 2,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 45000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 2,
                'img_id'=> 2,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 50000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 2,
                'img_id'=> 2,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 53000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 3,
                'img_id'=> 3,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 10000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 3,
                'img_id'=> 3,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 15000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 3,
                'img_id'=> 3,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 20000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 4,
                'img_id'=> 4,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 10000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 4,
                'img_id'=> 4,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 15000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 5,
                'img_id'=> 5,
                'size' => '100g',
                'stock_quantity' => 150,
                'price' => 69000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 5,
                'img_id'=> 5,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 79000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 5,
                'img_id'=> 5,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 85000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 6,
                'img_id'=> 6,
                'size' => '100g',
                'stock_quantity' => 150,
                'price' => 60000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 6,
                'img_id'=> 6,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 80000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 6,
                'img_id'=> 6,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 100000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 7,
                'img_id'=> 7,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 15000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 7,
                'img_id'=> 7,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 20000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 7,
                'img_id'=> 7,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 25000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 7,
                'img_id'=> 7,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 30000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 8,
                'img_id'=> 8,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 30000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 8,
                'img_id'=> 8,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 35000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 8,
                'img_id'=> 8,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 50000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 8,
                'img_id'=> 8,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 60000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 9,
                'img_id'=> 9,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 10000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 9,
                'img_id'=> 9,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 15000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 9,
                'img_id'=> 9,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 20000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 9,
                'img_id'=> 9,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 25000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
             [
                'product_id'=> 10,
                'img_id'=> 10,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 10000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 10,
                'img_id'=> 10,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 15000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 10,
                'img_id'=> 10,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 20000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 10,
                'img_id'=> 10,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 25000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
             [
                'product_id'=> 11,
                'img_id'=> 11,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 10000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 11,
                'img_id'=> 11,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 15000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 11,
                'img_id'=> 11,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 20000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 11,
                'img_id'=> 11,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 25000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 12,
                'img_id'=> 12,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 10000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 12,
                'img_id'=> 12,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 15000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 12,
                'img_id'=> 12,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 20000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 12,
                'img_id'=> 12,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 25000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 13,
                'img_id'=> 13,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 10000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 13,
                'img_id'=> 13,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 15000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 13,
                'img_id'=> 13,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 20000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 13,
                'img_id'=> 13,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 25000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 14,
                'img_id'=> 14,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 10000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 14,
                'img_id'=> 14,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 15000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 14,
                'img_id'=> 14,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 20000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 14,
                'img_id'=> 14,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 25000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 15,
                'img_id'=> 15,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 28000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 15,
                'img_id'=> 15,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 32000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 15,
                'img_id'=> 15,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 36000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 15,
                'img_id'=> 15,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 40000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 16,
                'img_id'=> 16,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 26000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 16,
                'img_id'=> 16,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 30000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 16,
                'img_id'=> 16,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 36000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 16,
                'img_id'=> 16,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 40000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 17,
                'img_id'=> 17,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 100000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 17,
                'img_id'=> 17,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 200000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 17,
                'img_id'=> 17,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 25000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 18,
                'img_id'=> 18,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 40000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 18,
                'img_id'=> 18,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 50000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 18,
                'img_id'=> 18,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 60000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 18,
                'img_id'=> 18,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 70000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 19,
                'img_id'=> 19,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 79000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 19,
                'img_id'=> 19,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 89000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 19,
                'img_id'=> 19,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 100000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 19,
                'img_id'=> 19,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 190000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 20,
                'img_id'=> 20,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 26000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 20,
                'img_id'=> 20,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 30000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 20,
                'img_id'=> 20,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 36000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 20,
                'img_id'=> 20,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 40000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 21,
                'img_id'=> 21,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 46000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 21,
                'img_id'=> 21,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 55000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 21,
                'img_id'=> 21,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 60000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 21,
                'img_id'=> 21,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 80000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 22,
                'img_id'=> 22,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 50000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 22,
                'img_id'=> 22,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 60000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 22,
                'img_id'=> 22,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 70000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 22,
                'img_id'=> 22,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 80000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 23,
                'img_id'=> 23,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 30000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 23,
                'img_id'=> 23,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 35000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 23,
                'img_id'=> 23,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 40000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 23,
                'img_id'=> 23,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 45000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 24,
                'img_id'=> 24,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 500000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 24,
                'img_id'=> 24,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 680000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 24,
                'img_id'=> 24,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 1500000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 24,
                'img_id'=> 24,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 1600000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 25,
                'img_id'=> 25,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 40000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 25,
                'img_id'=> 25,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 59000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 25,
                'img_id'=> 25,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 63000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 25,
                'img_id'=> 25,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 70000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 26,
                'img_id'=> 26,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 49000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 26,
                'img_id'=> 26,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 59000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 26,
                'img_id'=> 26,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 69000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 26,
                'img_id'=> 26,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 75000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
//
            [
                'product_id'=> 27,
                'img_id'=> 27,
                'size' => '50g',
                'stock_quantity' => 100,
                'price' => 30000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 27,
                'img_id'=> 27,
                'size' => '100g',
                'stock_quantity' => 100,
                'price' => 40000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 27,
                'img_id'=> 27,
                'size' => '150g',
                'stock_quantity' => 150,
                'price' => 60000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id'=> 27,
                'img_id'=> 27,
                'size' => '200g',
                'stock_quantity' => 150,
                'price' => 70000,
                'sale_price' => null,
                'status' => 'còn hàng',
                'active' => 'on',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
